/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LivraisonRouteImport } from './routes/livraison'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BoutiqueRouteImport } from './routes/boutique'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProduitSlugRouteImport } from './routes/produit.$slug'

const LivraisonRoute = LivraisonRouteImport.update({
  id: '/livraison',
  path: '/livraison',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiqueRoute = BoutiqueRouteImport.update({
  id: '/boutique',
  path: '/boutique',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitSlugRoute = ProduitSlugRouteImport.update({
  id: '/produit/$slug',
  path: '/produit/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/boutique': typeof BoutiqueRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/legal': typeof LegalRoute
  '/livraison': typeof LivraisonRoute
  '/produit/$slug': typeof ProduitSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/boutique': typeof BoutiqueRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/legal': typeof LegalRoute
  '/livraison': typeof LivraisonRoute
  '/produit/$slug': typeof ProduitSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/boutique': typeof BoutiqueRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/legal': typeof LegalRoute
  '/livraison': typeof LivraisonRoute
  '/produit/$slug': typeof ProduitSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/boutique'
    | '/contact'
    | '/faq'
    | '/legal'
    | '/livraison'
    | '/produit/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/boutique'
    | '/contact'
    | '/faq'
    | '/legal'
    | '/livraison'
    | '/produit/$slug'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/boutique'
    | '/contact'
    | '/faq'
    | '/legal'
    | '/livraison'
    | '/produit/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  BoutiqueRoute: typeof BoutiqueRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  LegalRoute: typeof LegalRoute
  LivraisonRoute: typeof LivraisonRoute
  ProduitSlugRoute: typeof ProduitSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/livraison': {
      id: '/livraison'
      path: '/livraison'
      fullPath: '/livraison'
      preLoaderRoute: typeof LivraisonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutique': {
      id: '/boutique'
      path: '/boutique'
      fullPath: '/boutique'
      preLoaderRoute: typeof BoutiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produit/$slug': {
      id: '/produit/$slug'
      path: '/produit/$slug'
      fullPath: '/produit/$slug'
      preLoaderRoute: typeof ProduitSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  BoutiqueRoute: BoutiqueRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  LegalRoute: LegalRoute,
  LivraisonRoute: LivraisonRoute,
  ProduitSlugRoute: ProduitSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
